# Generated by Django 4.2 on 2024-08-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_domain_domain_alter_domain_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set(),
        ),
    ]
