# Generated by Django 5.0.7 on 2024-07-28 19:41

from django.db import migrations, models

def copy_values_to_raw_value(apps, schema_editor):
    PressureReading = apps.get_model('sensors', 'PressureReading')
    for reading in PressureReading.objects.all():
        reading.raw_value = reading.value
        reading.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_pressurereading_tags_pressuresensor_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressurereading',
            name='raw_value',
            field=models.FloatField(null=True),
        ),
         migrations.RunPython(copy_values_to_raw_value),
    ]
