# Generated by Django 5.0.7 on 2024-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_pressurereading_tags_pressuresensor_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuresensor',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
    ]
