# Generated by Django 5.0.7 on 2024-08-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tags', '0001_initial'),
        ('sensors', '0006_pressuresensor_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurereading',
            name='tags',
            field=models.ManyToManyField(to='my_tags.tag'),
        ),
        migrations.AlterField(
            model_name='pressuresensor',
            name='serial_number',
            field=models.CharField(default='default_serial_number', editable=False, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
