# Generated by Django 5.0.7 on 2024-08-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_pressurereading_raw_value'),
        ('sensors', '0007_alter_pressurereading_tags_and_more'),
    ]

    operations = [
    ]
